theme: minima
title: On the Journey to Myself
author: Teresa Tetens
email: teresa.tetens@dgmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a mother and wife on the journey to change career to a web developer
  Down to earth, hands dirty and true to life 

# social links
twitter_TeresaTetens: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_teresatetens:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
